### ISSUE TITLE
Public API interface for yang-comparator

### ISSUE THREAD

**Issue by ahassany** [HuaweiDatacomm/yang-comparator#3]
At the moment, it's hard for me to understand what's the public API to use yang-comparator as a library in other projects.

Currently, the main file is `com.huawei.yang.comparator.YangComparator` which defines `public static void main(String[] args)` making is useful for running it as a standalone application. However, for including yang-comparator in another applications we don't need that code to be there by default and a clear and easy to use API is much more suitable.

Is there any plans to provide such APIs and preferably some examples?

**Comment by lllyfeng** [comment]
Ahmed,
  You can use the APIs like this:
```
YangComparator comparator = new YangComparator(leftSchemaContext,rightSchemaContext);
List<YangCompareResult> compareResults = comparator.compare(compareType,rule);
```
You can get the YangSchemaContext by calling some methods of Yangkit Parser or Yang Compiler.
For example:
```
        YangSchemaContext leftSchemaContext = YangYinParser.parse(leftYangDir,leftDepDir,leftCap);
        leftSchemaContext.validate();
        YangSchemaContext rightSchemaContext = YangYinParser.parse(rightYangDir,rightDepDir,rightCap);
        rightSchemaContext.validate();
        YangComparator comparator = new YangComparator(leftSchemaContext,rightSchemaContext);
        List<YangCompareResult> compareResults = comparator.compare(CompareType.COMPATIBLE_CHECK,null);
```

**Comment by lllyfeng** [comment]
Another example (using Yang Compiler):
```
YangCompiler yangCompiler = new YangCompiler();
yangCompiler.setSettings(new Settings());
yangCompiler.setYang(leftYangDir);
YangSchemaContext leftSchemaContext = yangCompiler.buildSchemaContext();
leftSchemaContext.validate();
yangCompiler.setYang(rightYangDir);
YangSchemaContext rightSchemaContext = yangCompiler.buildSchemaContext();
rightSchemaContext.validate();
YangComparator comparator = new YangComparator(leftSchemaContext,rightSchemaContext);
List<YangCompareResult> compareResults = comparator.compare(CompareType.COMPATIBLE_CHECK,null);
```

**Comment by ahassany** [comment]
Thank you Frank, I'll try it out. However, still unusual to have a `main` function inside the YangComparator.

**Comment by lllyfeng** [comment]
> Thank you Frank, I'll try it out. However, still unusual to have a `main` function inside the YangComparator.

Ahmed, I  can't follow what you mean. Can you explain it clearly?

You mean there should be another class as standalone application to invoke YangComparator?

**Comment by ahassany** [comment]
Yes exactly. Ideally two packages. One is the library only package and the second which is for the application that have a static void main and command line parsing code.

**Comment by lllyfeng** [comment]
> Yes exactly. Ideally two packages. One is the library only package and the second which is for the application that have a static void main and command line parsing code.

OK. You are right. I have refactored the code. :)  Should this issue be closed?
